markdown: kramdown

kramdown:
    use_coderay: true

# user defined variables

# entry-type
# [ default, in-progress, deprecated, in-discussion, marked-to-delete ]
entry-type: default

url: "http://php-de.github.io"

relative_permalinks: false

# page groups

groups:

    - name: "Allgemein"
      path: "/general"
      desc: "Grundlegende Informationen zum Einstieg in PHP"
      anchor: "general"

    - name: "Entwicklungs Umgebung"
      path: "/dev-enviroment"
      desc: "XAMPP, LAMPP, VirtualBox, ZendServer & Co."
      anchor: "dev-enviroment"

    - name: "Code-Optimierung"
      path: "/code-optimizing"
      desc: "Code-Optimierung von A bis Z."
      anchor: "code-optimizing"

    - name: "Datenbanken"
      path: "/database"
      desc: "MySQL & Co."
      anchor: "database"

    - name: "Debugging"
      path: "/debugging"
      desc: "Auf Fehlersuche"
      anchor: "debugging"

    - name: "E-Mail"
      path: "/email"
      desc: "Wissenswertes über den Umgang mit E-Mail-Adressen, Mail-Servern, und Mailer-Klassen."
      anchor: "email"

    - name: "Formularverarbeitung"
      path: "/form"
      desc: "Rund um die Erstellung, Verarbeitung, Validierung, etc. von Formularen"
      anchor: "form"

    - name: "Objektorientierte Programmierung (OOP)"
      path: "/oop"
      desc: "OOP unter PHP"
      anchor: "oop"

    - name: "Request-Handling"
      path: "/request-handling"
      desc: "Wissenswertes über das Request Handling in PHP."
      anchor: "request-handling"
